language: scala

jdk:
  - oraclejdk8

scala:
   - 2.10.6
   - 2.11.7

script:
  - ./gradlew reportScoverage -PscalaVersion=$TRAVIS_SCALA_VERSION

after_success:
  - bash <(curl -s https://codecov.io/bash)

